# Generated by Django 2.2.5 on 2019-11-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prproducts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='acitve',
            new_name='active',
        ),
    ]
